# Generated by Django 6.0.6 on 2026-06-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipy', '0002_cafe_city_cafe_country_cafe_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='latitude',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='longitude',
            field=models.CharField(max_length=50),
        ),
    ]
