# Generated by Django 6.0.6 on 2026-06-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipy', '0003_alter_cafe_latitude_alter_cafe_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='category',
            field=models.CharField(choices=[('Coffee', 'Coffee'), ('Matcha', 'Matcha'), ('Tea', 'Tea'), ('Boba', 'Boba'), ('Juice', 'Juice'), ('Smoothies', 'Smoothies'), ('Soda', 'Soda'), ('Alcohol', 'Alcohol'), ('Other', 'Other')], default='Coffee', max_length=50),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='score',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
