# Generated by Django 6.0.5 on 2026-05-27 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0002_alter_profile_display_name_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_file',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
